name: ⚙️ Auto Updater Engine

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

concurrency:
  group: engine-update
  cancel-in-progress: true

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install deps
        run: npm install

      - name: Run engine
        run: node src/index.js

      - name: Commit changes
        run: |
          git config user.name "RafaelaSommer"
          git config user.email "camilaerafaelagoncalves@hotmail.com"

          git add .

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "⚙️ auto update engine"
            git push
          fi
