name: 🤖 Update README

on:
  schedule:
    - cron: "*/20 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm install axios luxon

      - run: node scripts/update_readme.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}